version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: Nginx.Dockerfile 
    ports:
      - "8080:80" # 호스트의 8080 포트를 컨테이너의 80번 포트로 매핑
    depends_on:
      - backend
    networks:
      - app_network
        

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # 백엔드 Dockerfile 지정
    ports:
      - "3001:3001" # 백엔드 포트 연결
    networks:
      - app_network
    env_file:
      - ./backend/.env

  database: # database 서비스가 services 섹션 하위에 포함
    image: mysql:8
    ports:
      - "3307:3306" # 호스트의 3307 포트를 MySQL 컨테이너의 3306 포트로 매핑
    volumes:
      - db_data:/var/lib/mysql
    environment: # 환경 변수 추가
      MYSQL_ROOT_PASSWORD: "teampassword"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: